using Sandbox.Game.EntityComponents;
using Sandbox.ModAPI.Ingame;
using Sandbox.ModAPI.Interfaces;
using SpaceEngineers.Game.ModAPI.Ingame;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System;
using VRage.Collections;
using VRage.Game.Components;
using VRage.Game.ModAPI.Ingame;
using VRage.Game.ObjectBuilders.Definitions;
using VRage.Game;
using VRageMath;

namespace IngameScript {
    static class BasicBlockNames {
        public static string GetName(IMyTerminalBlock b) {
            if (b == null) return string.Empty;
            var key = b.BlockDefinition.TypeIdString.Substring(16) + ":" + b.BlockDefinition.SubtypeId;
            switch (key) {
                default: return string.Empty;
                case "AirtightHangarDoor:": return "Hangar Door";
                case "AirtightSlideDoor:LargeBlockSlideDoor": return "Door";
                case "AirVent:": return "Air Vent";
                case "AirVent:SmallAirVent": return "Air Vent";
                case "Assembler:LargeAssembler": return "Assembler";
                case "BatteryBlock:LargeBlockBatteryBlock": return "Battery";
                case "BatteryBlock:SmallBlockBatteryBlock": return "Battery";
                case "Beacon:LargeBlockBeacon": return "Beacon";
                case "Beacon:SmallBlockBeacon": return "Beacon";
                case "ButtonPanel:ButtonPanelLarge": return "Button Panel";
                case "ButtonPanel:ButtonPanelSmall": return "Button Panel";
                case "CameraBlock:LargeCameraBlock": return "Camera";
                case "CameraBlock:SmallCameraBlock": return "Camera";
                case "CargoContainer:LargeBlockLargeContainer": return "Lg Cargo";
                case "CargoContainer:LargeBlockSmallContainer": return "Sm Cargo";
                case "CargoContainer:SmallBlockLargeContainer": return "Lg Cargo";
                case "CargoContainer:SmallBlockMediumContainer": return "Med Cargo";
                case "CargoContainer:SmallBlockSmallContainer": return "Sm Cargo";
                case "Cockpit:CockpitOpen": return "Flight Seat";
                case "Cockpit:DBSmallBlockFighterCockpit": return "Fighter Cockpit";
                case "Cockpit:LargeBlockCockpit": return "Control Station";
                case "Cockpit:LargeBlockCockpitSeat": return "Cockpit";
                case "Cockpit:PassengerSeatLarge": return "Passenger Seat";
                case "Cockpit:PassengerSeatSmall": return "Passenger Seat";
                case "Cockpit:SmallBlockCockpit": return "Cockpit";
                case "Collector:Collector": return "Collector";
                case "Collector:CollectorSmall": return "Collector";
                //case "Conveyor:LargeBlockConveyor": return "";
                //case "Conveyor:SmallBlockConveyor": return "";
                //case "Conveyor:SmallShipConveyorHub": return "";
                //case "ConveyorConnector:ConveyorFrameMedium": return "";
                //case "ConveyorConnector:ConveyorTube": return "";
                //case "ConveyorConnector:ConveyorTubeCurved": return "";
                //case "ConveyorConnector:ConveyorTubeCurvedMedium": return "";
                //case "ConveyorConnector:ConveyorTubeMedium": return "";
                //case "ConveyorConnector:ConveyorTubeSmall": return "";
                //case "ConveyorConnector:ConveyorTubeSmallCurved": return "";
                case "ConveyorSorter:LargeBlockConveyorSorter": return "";
                case "ConveyorSorter:MediumBlockConveyorSorter": return "";
                case "ConveyorSorter:SmallBlockConveyorSorter": return "";
                case "CryoChamber:LargeBlockCryoChamber": return "Cryo Chamber";
                //case "CubeBlock:ArmorAlpha": return "";
                //case "CubeBlock:ArmorCenter": return "";
                //case "CubeBlock:ArmorCorner": return "";
                //case "CubeBlock:ArmorInvCorner": return "";
                //case "CubeBlock:ArmorSide": return "";
                //case "CubeBlock:DeadAstronaut": return "";
                //case "CubeBlock:LargeBlockArmorAngledCorner": return "";
                //case "CubeBlock:LargeBlockArmorAngledSlope": return "";
                //case "CubeBlock:LargeBlockArmorBlock": return "";
                //case "CubeBlock:LargeBlockArmorCorner": return "";
                //case "CubeBlock:LargeBlockArmorCorner2Base": return "";
                //case "CubeBlock:LargeBlockArmorCorner2BaseSmooth": return "";
                //case "CubeBlock:LargeBlockArmorCorner2Tip": return "";
                //case "CubeBlock:LargeBlockArmorCorner2TipSmooth": return "";
                //case "CubeBlock:LargeBlockArmorCornerInv": return "";
                //case "CubeBlock:LargeBlockArmorInvCorner2Base": return "";
                //case "CubeBlock:LargeBlockArmorInvCorner2BaseSmooth": return "";
                //case "CubeBlock:LargeBlockArmorInvCorner2Tip": return "";
                //case "CubeBlock:LargeBlockArmorInvCorner2TipSmooth": return "";
                //case "CubeBlock:LargeBlockArmorRoundCorner": return "";
                //case "CubeBlock:LargeBlockArmorRoundCornerInv": return "";
                //case "CubeBlock:LargeBlockArmorRoundedCorner": return "";
                //case "CubeBlock:LargeBlockArmorRoundedSlope": return "";
                //case "CubeBlock:LargeBlockArmorRoundSlope": return "";
                //case "CubeBlock:LargeBlockArmorSlope": return "";
                //case "CubeBlock:LargeBlockArmorSlope2Base": return "";
                //case "CubeBlock:LargeBlockArmorSlope2BaseSmooth": return "";
                //case "CubeBlock:LargeBlockArmorSlope2Tip": return "";
                //case "CubeBlock:LargeBlockArmorSlope2TipSmooth": return "";
                //case "CubeBlock:LargeBlockInteriorWall": return "";
                //case "CubeBlock:LargeCoverWall": return "";
                //case "CubeBlock:LargeCoverWallHalf": return "";
                //case "CubeBlock:LargeHeavyBlockArmorAngledCorner": return "";
                //case "CubeBlock:LargeHeavyBlockArmorAngledSlope": return "";
                //case "CubeBlock:LargeHeavyBlockArmorBlock": return "";
                //case "CubeBlock:LargeHeavyBlockArmorCorner": return "";
                //case "CubeBlock:LargeHeavyBlockArmorCorner2Base": return "";
                //case "CubeBlock:LargeHeavyBlockArmorCorner2BaseSmooth": return "";
                //case "CubeBlock:LargeHeavyBlockArmorCorner2Tip": return "";
                //case "CubeBlock:LargeHeavyBlockArmorCorner2TipSmooth": return "";
                //case "CubeBlock:LargeHeavyBlockArmorCornerInv": return "";
                //case "CubeBlock:LargeHeavyBlockArmorInvCorner2Base": return "";
                //case "CubeBlock:LargeHeavyBlockArmorInvCorner2BaseSmooth": return "";
                //case "CubeBlock:LargeHeavyBlockArmorInvCorner2Tip": return "";
                //case "CubeBlock:LargeHeavyBlockArmorInvCorner2TipSmooth": return "";
                //case "CubeBlock:LargeHeavyBlockArmorRoundCorner": return "";
                //case "CubeBlock:LargeHeavyBlockArmorRoundCornerInv": return "";
                //case "CubeBlock:LargeHeavyBlockArmorRoundedCorner": return "";
                //case "CubeBlock:LargeHeavyBlockArmorRoundedSlope": return "";
                //case "CubeBlock:LargeHeavyBlockArmorRoundSlope": return "";
                //case "CubeBlock:LargeHeavyBlockArmorSlope": return "";
                //case "CubeBlock:LargeHeavyBlockArmorSlope2Base": return "";
                //case "CubeBlock:LargeHeavyBlockArmorSlope2BaseSmooth": return "";
                //case "CubeBlock:LargeHeavyBlockArmorSlope2Tip": return "";
                //case "CubeBlock:LargeHeavyBlockArmorSlope2TipSmooth": return "";
                //case "CubeBlock:LargeInteriorPillar": return "";
                //case "CubeBlock:LargeRailStraight": return "";
                //case "CubeBlock:LargeRamp": return "";
                //case "CubeBlock:LargeRoundArmor_Corner": return "";
                //case "CubeBlock:LargeRoundArmor_CornerInv": return "";
                //case "CubeBlock:LargeRoundArmor_Slope": return "";
                //case "CubeBlock:LargeStairs": return "";
                //case "CubeBlock:LargeSteelCatwalk": return "";
                //case "CubeBlock:LargeSteelCatwalk2Sides": return "";
                //case "CubeBlock:LargeSteelCatwalkCorner": return "";
                //case "CubeBlock:LargeSteelCatwalkPlate": return "";
                //case "CubeBlock:LargeWindowEdge": return "";
                //case "CubeBlock:LargeWindowSquare": return "";
                //case "CubeBlock:Monolith": return "";
                //case "CubeBlock:SmallArmorCenter": return "";
                //case "CubeBlock:SmallArmorCorner": return "";
                //case "CubeBlock:SmallArmorInvCorner": return "";
                //case "CubeBlock:SmallArmorSide": return "";
                //case "CubeBlock:SmallBlockArmorAngledCorner": return "";
                //case "CubeBlock:SmallBlockArmorAngledSlope": return "";
                //case "CubeBlock:SmallBlockArmorBlock": return "";
                //case "CubeBlock:SmallBlockArmorCorner": return "";
                //case "CubeBlock:SmallBlockArmorCorner2Base": return "";
                //case "CubeBlock:SmallBlockArmorCorner2BaseSmooth": return "";
                //case "CubeBlock:SmallBlockArmorCorner2Tip": return "";
                //case "CubeBlock:SmallBlockArmorCorner2TipSmooth": return "";
                //case "CubeBlock:SmallBlockArmorCornerInv": return "";
                //case "CubeBlock:SmallBlockArmorInvCorner2Base": return "";
                //case "CubeBlock:SmallBlockArmorInvCorner2BaseSmooth": return "";
                //case "CubeBlock:SmallBlockArmorInvCorner2Tip": return "";
                //case "CubeBlock:SmallBlockArmorInvCorner2TipSmooth": return "";
                //case "CubeBlock:SmallBlockArmorRoundCorner": return "";
                //case "CubeBlock:SmallBlockArmorRoundCornerInv": return "";
                //case "CubeBlock:SmallBlockArmorRoundedCorner": return "";
                //case "CubeBlock:SmallBlockArmorRoundedSlope": return "";
                //case "CubeBlock:SmallBlockArmorRoundSlope": return "";
                //case "CubeBlock:SmallBlockArmorSlope": return "";
                //case "CubeBlock:SmallBlockArmorSlope2Base": return "";
                //case "CubeBlock:SmallBlockArmorSlope2BaseSmooth": return "";
                //case "CubeBlock:SmallBlockArmorSlope2Tip": return "";
                //case "CubeBlock:SmallBlockArmorSlope2TipSmooth": return "";
                //case "CubeBlock:SmallHeavyBlockArmorAngledCorner": return "";
                //case "CubeBlock:SmallHeavyBlockArmorAngledSlope": return "";
                //case "CubeBlock:SmallHeavyBlockArmorBlock": return "";
                //case "CubeBlock:SmallHeavyBlockArmorCorner": return "";
                //case "CubeBlock:SmallHeavyBlockArmorCorner2Base": return "";
                //case "CubeBlock:SmallHeavyBlockArmorCorner2BaseSmooth": return "";
                //case "CubeBlock:SmallHeavyBlockArmorCorner2Tip": return "";
                //case "CubeBlock:SmallHeavyBlockArmorCorner2TipSmooth": return "";
                //case "CubeBlock:SmallHeavyBlockArmorCornerInv": return "";
                //case "CubeBlock:SmallHeavyBlockArmorInvCorner2Base": return "";
                //case "CubeBlock:SmallHeavyBlockArmorInvCorner2BaseSmooth": return "";
                //case "CubeBlock:SmallHeavyBlockArmorInvCorner2Tip": return "";
                //case "CubeBlock:SmallHeavyBlockArmorInvCorner2TipSmooth": return "";
                //case "CubeBlock:SmallHeavyBlockArmorRoundCorner": return "";
                //case "CubeBlock:SmallHeavyBlockArmorRoundCornerInv": return "";
                //case "CubeBlock:SmallHeavyBlockArmorRoundedCorner": return "";
                //case "CubeBlock:SmallHeavyBlockArmorRoundedSlope": return "";
                //case "CubeBlock:SmallHeavyBlockArmorRoundSlope": return "";
                //case "CubeBlock:SmallHeavyBlockArmorSlope": return "";
                //case "CubeBlock:SmallHeavyBlockArmorSlope2Base": return "";
                //case "CubeBlock:SmallHeavyBlockArmorSlope2BaseSmooth": return "";
                //case "CubeBlock:SmallHeavyBlockArmorSlope2Tip": return "";
                //case "CubeBlock:SmallHeavyBlockArmorSlope2TipSmooth": return "";
                //case "CubeBlock:Stereolith": return "";
                //case "CubeBlock:Window1x1Face": return "";
                //case "CubeBlock:Window1x1Flat": return "";
                //case "CubeBlock:Window1x1FlatInv": return "";
                //case "CubeBlock:Window1x1Inv": return "";
                //case "CubeBlock:Window1x1Side": return "";
                //case "CubeBlock:Window1x1SideInv": return "";
                //case "CubeBlock:Window1x1Slope": return "";
                //case "CubeBlock:Window1x2Face": return "";
                //case "CubeBlock:Window1x2Flat": return "";
                //case "CubeBlock:Window1x2FlatInv": return "";
                //case "CubeBlock:Window1x2Inv": return "";
                //case "CubeBlock:Window1x2SideLeft": return "";
                //case "CubeBlock:Window1x2SideLeftInv": return "";
                //case "CubeBlock:Window1x2SideRight": return "";
                //case "CubeBlock:Window1x2SideRightInv": return "";
                //case "CubeBlock:Window1x2Slope": return "";
                //case "CubeBlock:Window2x3Flat": return "";
                //case "CubeBlock:Window2x3FlatInv": return "";
                //case "CubeBlock:Window3x3Flat": return "";
                //case "CubeBlock:Window3x3FlatInv": return "";
                //case "DebugSphere1:DebugSphereLarge": return "";
                //case "DebugSphere2:DebugSphereLarge": return "";
                //case "DebugSphere3:DebugSphereLarge": return "";
                case "Decoy:LargeDecoy": return "Decoy";
                case "Decoy:SmallDecoy": return "Decoy";
                case "Door:": return "Door";
                case "Drill:LargeBlockDrill": return "Drill";
                case "Drill:SmallBlockDrill": return "Drill";
                case "ExtendedPistonBase:LargePistonBase": return "Piston";
                case "ExtendedPistonBase:SmallPistonBase": return "Piston";
                //case "GasProperties:Hydrogen": return "";
                //case "GasProperties:Oxygen": return "";
                case "GravityGenerator:": return "Gravity Generator";
                case "GravityGeneratorSphere:": return "Sphere Gravity Generator";
                case "Gyro:LargeBlockGyro": return "Gyro";
                case "Gyro:SmallBlockGyro": return "Gyro";
                case "InteriorLight:LargeBlockLight_1corner": return "Corner Light";
                case "InteriorLight:LargeBlockLight_2corner": return "Corner Light 2x";
                case "InteriorLight:SmallBlockLight_1corner": return "Corner Light";
                case "InteriorLight:SmallBlockLight_2corner": return "Corner Light 2x";
                case "InteriorLight:SmallBlockSmallLight": return "Light";
                case "InteriorLight:SmallLight": return "Light";
                case "InteriorTurret:LargeInteriorTurret": return "Interior Turret";
                case "JumpDrive:LargeJumpDrive": return "Jump Drive";
                case "LandingGear:LargeBlockLandingGear": return "Landing Gear";
                case "LandingGear:SmallBlockLandingGear": return "Landing Gear";
                case "LargeGatlingTurret:": return "Gatling Turret";
                case "LargeGatlingTurret:SmallGatlingTurret": return "Gatling Turret";
                case "LargeMissileTurret:": return "Missile Turret";
                case "LargeMissileTurret:SmallMissileTurret": return "Missile Turret";
                case "LaserAntenna:LargeBlockLaserAntenna": return "Laser Antenna";
                case "LaserAntenna:SmallBlockLaserAntenna": return "Laser Antenna";
                case "MedicalRoom:LargeMedicalRoom": return "Medical";
                case "MergeBlock:LargeShipMergeBlock": return "Merge";
                case "MergeBlock:SmallShipMergeBlock": return "Merge";
                case "MotorAdvancedRotor:LargeAdvancedRotor": return "";
                case "MotorAdvancedRotor:SmallAdvancedRotor": return "";
                case "MotorAdvancedStator:LargeAdvancedStator": return "";
                case "MotorAdvancedStator:SmallAdvancedStator": return "";
                case "MotorRotor:LargeRotor": return "";
                case "MotorRotor:SmallRotor": return "";
                case "MotorStator:LargeStator": return "";
                case "MotorStator:SmallStator": return "";
                case "MotorSuspension:SmallSuspension1x1": return "";
                case "MotorSuspension:SmallSuspension1x1mirrored": return "";
                case "MotorSuspension:SmallSuspension3x3": return "";
                case "MotorSuspension:SmallSuspension3x3mirrored": return "";
                case "MotorSuspension:SmallSuspension5x5": return "";
                case "MotorSuspension:SmallSuspension5x5mirrored": return "";
                case "MotorSuspension:Suspension1x1": return "";
                case "MotorSuspension:Suspension1x1mirrored": return "";
                case "MotorSuspension:Suspension3x3": return "";
                case "MotorSuspension:Suspension3x3mirrored": return "";
                case "MotorSuspension:Suspension5x5": return "";
                case "MotorSuspension:Suspension5x5mirrored": return "";
                case "MyObjectBuilder_Projector:LargeProjector": return "";
                case "MyObjectBuilder_Projector:SmallProjector": return "";
                case "MyProgrammableBlock:LargeProgrammableBlock": return "";
                case "MyProgrammableBlock:SmallProgrammableBlock": return "";
                case "OreDetector:LargeOreDetector": return "";
                case "OreDetector:SmallBlockOreDetector": return "";
                case "OxygenFarm:LargeBlockOxygenFarm": return "Oxygen Farm";
                case "OxygenGenerator:": return "Oxygen Generator";
                case "OxygenGenerator:OxygenGeneratorSmall": return "Oxygen Generator";
                case "OxygenTank:": return "Oxygen Tank";
                case "OxygenTank:LargeHydrogenTank": return "Hydrogen Tank";
                case "OxygenTank:OxygenTankSmall": return "Oxygen Tank";
                case "OxygenTank:SmallHydrogenTank": return "Hydrogen Tank";
                case "Parachute:LgParachute": return "Parachute";
                case "Parachute:SmParachute": return "Parachute";
                case "Passage:": return "";
                case "PistonBase:LargePistonBase": return "";
                case "PistonBase:SmallPistonBase": return "";
                case "PistonTop:LargePistonTop": return "";
                case "PistonTop:SmallPistonTop": return "";
                case "RadioAntenna:LargeBlockRadioAntenna": return "Antenna";
                case "RadioAntenna:SmallBlockRadioAntenna": return "Antenna";
                case "Reactor:LargeBlockLargeGenerator": return "Lg Reactor";
                case "Reactor:LargeBlockSmallGenerator": return "Sm Reactor";
                case "Reactor:SmallBlockLargeGenerator": return "Lg Reactor";
                case "Reactor:SmallBlockSmallGenerator": return "Sm Reactor";
                case "Refinery:Blast Furnace": return "Arc Furnace";
                case "Refinery:LargeRefinery": return "Refinery";
                case "ReflectorLight:LargeBlockFrontLight": return "Spotlight";
                case "ReflectorLight:SmallBlockFrontLight": return "Spotlight";
                case "RemoteControl:LargeBlockRemoteControl": return "Remote Control";
                case "RemoteControl:SmallBlockRemoteControl": return "Remote Control";
                case "SensorBlock:LargeBlockSensor": return "";
                case "SensorBlock:SmallBlockSensor": return "";
                case "ShipConnector:Connector": return "Connector";
                case "ShipConnector:ConnectorMedium": return "Connector";
                case "ShipConnector:ConnectorSmall": return "Ejector";
                case "ShipGrinder:LargeShipGrinder": return "";
                case "ShipGrinder:SmallShipGrinder": return "";
                case "ShipWelder:LargeShipWelder": return "";
                case "ShipWelder:SmallShipWelder": return "";
                case "SmallGatlingGun:": return "";
                case "SmallMissileLauncher:": return "";
                case "SmallMissileLauncher:LargeMissileLauncher": return "";
                case "SmallMissileLauncherReload:SmallRocketLauncherReload": return "";
                case "SolarPanel:LargeBlockSolarPanel": return "";
                case "SolarPanel:SmallBlockSolarPanel": return "";
                case "SoundBlock:LargeBlockSoundBlock": return "";
                case "SoundBlock:SmallBlockSoundBlock": return "";
                case "SpaceBall:SpaceBallLarge": return "";
                case "SpaceBall:SpaceBallSmall": return "";
                case "TerminalBlock:ControlPanel": return "";
                case "TerminalBlock:SmallControlPanel": return "";
                case "TextPanel:LargeBlockCorner_LCD_1": return "Corner LCD";
                case "TextPanel:LargeBlockCorner_LCD_2": return "Corner LCD";
                case "TextPanel:LargeBlockCorner_LCD_Flat_1": return "Flat LCD";
                case "TextPanel:LargeBlockCorner_LCD_Flat_2": return "Flat LCD";
                case "TextPanel:LargeLCDPanel": return "LCD";
                case "TextPanel:LargeLCDPanelWide": return "Wide LCD";
                case "TextPanel:LargeTextPanel": return "Text Panel";
                case "TextPanel:SmallBlockCorner_LCD_1": return "Corner LCD";
                case "TextPanel:SmallBlockCorner_LCD_2": return "Corner LCD";
                case "TextPanel:SmallBlockCorner_LCD_Flat_1": return "Flat LCD";
                case "TextPanel:SmallBlockCorner_LCD_Flat_2": return "Flat LCD";
                case "TextPanel:SmallLCDPanel": return "LCD";
                case "TextPanel:SmallLCDPanelWide": return "Wide LCD";
                case "TextPanel:SmallTextPanel": return "Text Panel";
                case "Thrust:LargeBlockLargeAtmosphericThrust": return "";
                case "Thrust:LargeBlockLargeHydrogenThrust": return "";
                case "Thrust:LargeBlockLargeThrust": return "";
                case "Thrust:LargeBlockSmallAtmosphericThrust": return "";
                case "Thrust:LargeBlockSmallHydrogenThrust": return "";
                case "Thrust:LargeBlockSmallThrust": return "";
                case "Thrust:SmallBlockLargeAtmosphericThrust": return "";
                case "Thrust:SmallBlockLargeHydrogenThrust": return "";
                case "Thrust:SmallBlockLargeThrust": return "";
                case "Thrust:SmallBlockSmallAtmosphericThrust": return "";
                case "Thrust:SmallBlockSmallHydrogenThrust": return "";
                case "Thrust:SmallBlockSmallThrust": return "";
                case "TimerBlock:TimerBlockLarge": return "";
                case "TimerBlock:TimerBlockSmall": return "";
                case "UpgradeModule:LargeEffectivenessModule": return "Yield Module";
                case "UpgradeModule:LargeEnergyModule": return "Power Module";
                case "UpgradeModule:LargeProductivityModule": return "Speed Module";
                case "VirtualMass:VirtualMassLarge": return "";
                case "VirtualMass:VirtualMassSmall": return "";
                case "Warhead:LargeWarhead": return "";
                case "Warhead:SmallWarhead": return "";
                case "Wheel:RealWheel": return "";
                case "Wheel:RealWheel1x1": return "";
                case "Wheel:RealWheel1x1mirrored": return "";
                case "Wheel:RealWheel5x5": return "";
                case "Wheel:RealWheel5x5mirrored": return "";
                case "Wheel:RealWheelmirrored": return "";
                case "Wheel:SmallRealWheel": return "";
                case "Wheel:SmallRealWheel1x1": return "";
                case "Wheel:SmallRealWheel1x1mirrored": return "";
                case "Wheel:SmallRealWheel5x5": return "";
                case "Wheel:SmallRealWheel5x5mirrored": return "";
                case "Wheel:SmallRealWheelmirrored": return "";
                case "Wheel:SmallWheel1x1": return "";
                case "Wheel:SmallWheel3x3": return "";
                case "Wheel:SmallWheel5x5": return "";
                case "Wheel:Wheel1x1": return "";
                case "Wheel:Wheel3x3": return "";
                case "Wheel:Wheel5x5": return "";
            }

        }
    }
}
